//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signia.OmakaseCategoryFeeder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signia.OmakaseCategoryFeeder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] categories_hierarchy {
            get {
                object obj = ResourceManager.GetObject("categories_hierarchy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL 1;LEVEL 2;LEVEL 3;LEVEL 4;LEVEL 5
        ///art and entertainment;books and literature;best-sellers;;
        ///art and entertainment;books and literature;children&apos;s books;;
        ///art and entertainment;books and literature;e-books;;
        ///art and entertainment;books and literature;fan fiction;;
        ///art and entertainment;books and literature;magazines;;
        ///art and entertainment;books and literature;mythology;;
        ///art and entertainment;books and literature;non-fiction;;
        ///art and entertainment;books and literature;poetry;;
        ///art and entert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string categories_hierarchy1 {
            get {
                return ResourceManager.GetString("categories_hierarchy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mosaiq_2017_Categories_Colors_plus_gradient {
            get {
                object obj = ResourceManager.GetObject("Mosaiq_2017_Categories_Colors_plus_gradient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAB Categories ( Categories with some modifications. We should use them. Names should start with capital letter) ;;Colours;HSL (new subcategories vary +1- Lightness to - 7);Gradient-on read and on hover;Gradient HSL;Corresponding Gizmag Categories;Corresponding TeknikensVarld Categories;All TeknikensVarld Categories
        ///Art &amp; Entertainment;;#ff6178;351, 100, 69;#ffc2b8;8, 100, 86;;;Bil och trafik (Car and Traffic)
        ///books &amp; literature;;#f9627f;348, 93, 68;#fbc2bb;251, 194, 187;;;Miljo och teknik (Environmental  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mosaiq_2017_Categories_Colors_plus_gradient1 {
            get {
                return ResourceManager.GetString("Mosaiq_2017_Categories_Colors_plus_gradient1", resourceCulture);
            }
        }
    }
}
